nvidia-smi

python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold1.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold1.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_1.pt' --save_path 'combination_setting1'
python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold2.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold2.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_2.pt' --save_path 'combination_setting2'
python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold3.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold3.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_3.pt' --save_path 'combination_setting3'
python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold4.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold4.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_4.pt' --save_path 'combination_setting4'
python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold5.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold5.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_5.pt' --save_path 'combination_setting5'
python train_comb.py --epoch 100 --seed 10 --b 256 --lr 0.0001 --weight_d 0.1 --gamma 0.5 --beta 0.9999 --gpu 1 --n_skip 8 --ir_loss_weight 1.1 --rec_loss_weight 0.1 --trained_teacher_net '/media/D2/public/max/workplace/fourth_paper/trained_teacher_network/equine/canet-best_25Hz_baseline_sam_fold6.pth' --trained_recon_net '/media/D2/public/max/workplace/fourth_paper/pretrained_rec_net/equine/reconnet-best_fold6.pth' --data_path '/media/D2/public/max/workplace/fourth_paper/data/equine_data/myTensor_6.pt' --save_path 'combination_setting6'


